### ISSUE TITLE
Translations for date/time fields

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#1510] opened 2019-03-15 22:43 UTC
Need to update translations.json for Spanish and English
- [ ] Month
- [ ] Date
- [ ] Year
- [ ] Hour
- [ ] Minute

Also see [#1508](https://app.zenhub.com/workspaces/office-of-design-and-delivery-5a78b88e1ce69f3510b678ef/issues/cityofaustin/techstack/1508)

**URL tested:** https://forms.austintexas.io/policia-queja/que-sucedio

Open [URL](https://live.browserstack.com/dashboard#os=OS+X&os_version=Mojave&browser=Chrome&browser_version=72.0&zoom_to_fit=true&full_screen=true&url=https%3A%2F%2Fforms.austintexas.io%2Fpolicia-queja%2Fque-sucedio&speed=1&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://forms.austintexas.io/policia-queja/que-sucedio) on Browserstack

|Property | Value|
|------------ | -------------|
| Browser | Chrome 72.0 |
| Operating System | OS X Mojave |
| Resolution | 1438x946 |

**Screenshot Attached** 
[Screenshot URL](https://live.browserstack.com/issue-tracker/b0fff3a44f2a18edddcc5ecd3af1740e3af05e96/macmo_chrome_72.0.jpg)
 ![Screenshot URL](https://live.browserstack.com/issue-tracker/b0fff3a44f2a18edddcc5ecd3af1740e3af05e96/macmo_chrome_72.0.jpg)

**[Click here](https://live.browserstack.com/dashboard#os=OS+X&os_version=Mojave&browser=Chrome&browser_version=72.0&zoom_to_fit=true&full_screen=true&url=https%3A%2F%2Fforms.austintexas.io%2Fpolicia-queja%2Fque-sucedio&speed=1&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://forms.austintexas.io/policia-queja/que-sucedio) to reproduce the issue on Browserstack**

**Comment by Niicck** [comment] 2019-03-25 17:20
Duplicate of #1508

**Closed by Niicck** 2019-03-25 17:20 UTC
Labels: Bug Reported, Department: Police Oversight, Police Oversight Form
