### ISSUE TITLE
As a resident, I want to see context surrounding OPO complaint/thanks so that I can share my feedback in confidence

### ISSUE THREAD

**Issue by toribr** [cityofaustin/techstack#1928] opened 2019-05-14 19:17 UTC
### As a resident, I want to see context surrounding OPO complaint/thanks so that I can share my feedback in confidence

This is about needing to move the introduction page, used for complaints and thanks, from the form domain into Janis, so that folks arriving to the page have more context. @srigdon is going to try to recreate the page using a service template to see how close it looks. The ability to add a button using html within an option needs exploring.

**Comment by easherma** [comment] 2019-05-14 22:24
This is a related/dupe of https://github.com/cityofaustin/techstack/issues/1920

**Comment by desigonz** [comment] 2019-06-20 22:39
lol double dupe of #1931

**Closed by desigonz** 2019-06-20 22:39 UTC
Labels: Department: Police Oversight, Joplin Alpha, Police Oversight Form, Team: Content
