### ISSUE TITLE
Task label should match user action

### ISSUE THREAD

**Issue by toribr** [cityofaustin/techstack#3105] opened 2019-10-03 17:58 UTC
The language used on the button should match the task the author is doing, in this case: 

Choose another topic, not Choose another page
![Screen Shot 2019-10-03 at 12.56.16 PM.png](https://images.zenhubusercontent.com/5a81e99a4b5806bc2bc6a146/e255be3b-182b-416e-86e2-3366808fbfb2)

(Similarly, if "edit" button does not match, but not-displaying this button is a better solution than changing the button label)

Note: this may be part of another page picker issue?

**Comment by desigonz** [comment] 2019-10-07 22:40
duplicate of #2604

**Closed** 2019-10-07 22:40 UTC
