### ISSUE TITLE
Move OPO intro pages to alpha.austin.gov

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#1920] opened 2019-05-13 17:31 UTC
This might be an epic...

The introduction page on filing a complaint lives on forms.austin.gov. Navigation-wise, though, I think it would be better to have that intro page on alpha _rather_ than on forms, so we can add it to our IA (aka makes it more discoverable).

Thoughts from @briaguya : 
- Update the OPO form to go straight to the first step
- Add it as a page in joplin and see what it looks like in janis, make any changes we need

From @easherma: I also made an issue to have the opo actions be on the ‘top services’ par of the alpha home page either way

From @toribr:
- I think separated out is the right move, but also it seems a bit lacking in terms of context if you can get to it directly. Know what I mean? Like it might need a little something to make it feel more official, like an OPO header or something. Let's whiteboard it Monday, and look at the flow.

**Comment by easherma** [comment] 2019-05-13 18:00
Related: https://github.com/cityofaustin/techstack/issues/1891

**Comment by easherma** [comment] 2019-05-14 22:00
@desigonz respectfully, I don't think this is required for Janis MVP so I'm going to remove the label.

**Comment by toribr** [comment] 2019-05-15 12:45
@easherma Since you missed all the conversations that have happened regarding this issue, I don't think it falls into your domain to decide what is and is not MVP for Janis 2.0. A better approach might be to discuss it with the team.

**Comment by desigonz** [comment] 2019-05-15 13:39
@toribr @easherma We'll be clarifying tasks for the Janis 2.0 MVP during sprint planning tomorrow, so I think that will be a good venue to decide if this will make it in the next release!

**Comment by briaguya** [comment] 2019-05-16 17:29
my current experience building these locally with copypasta data:

## Info Page
<img width="1527" alt="Screen Shot 2019-05-15 at 12 21 38 PM" src="https://user-images.githubusercontent.com/6384156/57874328-ebd73600-77d5-11e9-9224-007522fa3ba3.png">

## Service Page
<img width="1499" alt="Screen Shot 2019-05-15 at 12 21 26 PM" src="https://user-images.githubusercontent.com/6384156/57874329-ebd73600-77d5-11e9-9fa9-8a3b140ab9d3.png">

**Comment by desigonz** [comment] 2019-05-16 18:09
looping in @srigdon, see above.

**Comment by easherma** [comment] 2019-05-16 21:12
I think this is a dupe of https://github.com/cityofaustin/techstack/issues/1928

**Closed by easherma** 2019-05-16 21:12 UTC
Labels: Janis 2.0, Team: Content, Team: Design + Research, Team: Dev
