### ISSUE TITLE
Fix usability of recollect app when user types address and blocks button

### ISSUE THREAD

**Issue by cthibaultatx** [cityofaustin/techstack#300] opened 2018-04-16 15:43 UTC
In testing, we observed a resident typing in street address, the app recommending the matching address in a drop-down, the user not realizing they have to select that address in the drop-down for the drop-down to go away before enabling them to click the "submit" button.

**Comment by amenity** [comment] 2018-06-04 20:20
Duplicate of #314

**Closed by amenity** 2018-06-04 20:20 UTC
Labels: Feature: Recollect, Feature: Service, Size: S, Team: Design/Research, Team: Dev
