### ISSUE TITLE
Police Oversight start page

### ISSUE THREAD

**Issue by toribr** [cityofaustin/techstack#1381] opened 2019-03-04 17:32 UTC
**Describe the bug**
Accordions should be closed by default. Changes in 

**URL**
https://forms.austintexas.io/police-oversight/complaint/introduction
**To Reproduce**

**Current behavior**

**Expected behavior**

**Screenshots**

**Device**

**Browser**

**Additional context**

**Comment by amenity** [comment] 2019-03-13 22:35
Duplicate of #1382

**Closed by amenity** 2019-03-13 22:35 UTC
Labels: Team: Dev
