### ISSUE TITLE
Global nav alignment

### ISSUE THREAD

**Issue by anukandimalla** [cityofaustin/techstack#2893] opened 2019-09-04 16:30 UTC
Description: The Main Nav and Secondary Nav need to align with top Dropdown. 

URL:https://janis.austintexas.io/en/health-safety/healthcare-prevention/disease-prevention/mobile-food-permitting-process-guide/

To Reproduce:
  Open the link in IE 11
  Notice Main Nav and Secondary Nav

Current behavior: Please refer to the attached screenshot. ![alignment1.png](https://images.zenhubusercontent.com/5d236a251149c07fcf3f4fbc/e3c2b462-83d7-4b8e-ae00-00b43b314646)

Expected behavior: Please refer to the screenshot.
![Expected Alignment.png](https://images.zenhubusercontent.com/5d236a251149c07fcf3f4fbc/09372474-9ab4-4542-aebe-f353215c781d)

**Comment by desigonz** [comment] 2019-09-04 22:53
Also:

The Top Banner needs to be aligned with the Main Nav, Secondary Nav, and Top dropdown.

URL: https://janis.austintexas.io/en/health-safety/healthcare-prevention/disease-prevention/mobile-food-permitting-process-guide/

To Reproduce:
1. Open the link URL above
2.Notice the Top Banner

Current behavior: Please refer to the attached screenshot.![Banner.png](https://images.zenhubusercontent.com/5d236a251149c07fcf3f4fbc/513011e6-d740-44c9-91a2-1832022c2a6e)

Expected behavior: The banner Max width needs to be 1160px, refer to the 
https://xd.adobe.com/spec/3693e3d0-1e3d-4c07-6555-b09fccd75568-40a2/screen/58cef195-a92f-450c-ba2e-4124f44b9469/Template-Guide-desktop/

**Comment by chasechenevert** [comment] 2019-09-06 15:20
Yep, those links should be flush left with the rule line between utility links and themes.

**Comment by chase-vert** [comment] 2020-05-05 16:48
Closing this because it's being addressed currently with the nav redesign https://github.com/cityofaustin/techstack/issues/4297

**Closed by chase-vert** 2020-05-05 16:48 UTC
Labels: Bug Reported, Feature: Global Navigation, Janis Alpha, P5, Team: Dev
