### ISSUE TITLE
Unpublish ARR and APH content from alpha

### ISSUE THREAD

**Issue by oliver2g** [cityofaustin/techstack#2092] opened 2019-05-23 15:46 UTC
Before we demo Janis 2.0 in production, we need to make sure the ARR and APH content is unpublished.  When it's cleaned up, re-translated, and approved, we can re-publish it.

**Comment by desigonz** [comment] 2019-05-28 15:29
@oliver2g This is a dupe of #1956 which I closed last week. Anything that's still published has translations and is good to go!

**Closed by desigonz** 2019-05-28 15:29 UTC
Labels: Janis 2.0, Team: Content, Team: Dev
