### ISSUE TITLE
Joplin - Design - Tables in rich text blocks

### ISSUE THREAD

**Issue by briaguya** [cityofaustin/techstack#2063] opened 2019-05-22 04:03 UTC
### As a content editor, I need to be able to add basic tables to a service or info page, so that I can sensibly display fees charts or similar content.

- [ ] design team delivers designs for how a content editor adds a table within a Joplin rich text block

Right now we have https://github.com/cityofaustin/techstack/issues/1935 implemented, but we're better than that. Let's do something good here.

Adding the table component to service and/or info pages. May require additional design issue?

**Comment by desigonz** [comment] 2019-08-01 20:48
duplicate of #2333

**Closed by desigonz** 2019-08-01 20:48 UTC
Labels: Author Interface, Joplin Alpha, Team: Design + Research
