### ISSUE TITLE
Padding above map hides additional details in a service page

### ISSUE THREAD

**Issue by Jo-Dwyer** [cityofaustin/techstack#3469] opened 2019-11-23 00:52 UTC
## Describe the bug
When I look at the service page 'Find work as a day laborer' I don't notice the map because of padding

[Find work as a day laborer](https://alpha.austin.gov/en/jobs/job-resources/help-finding-work/find-work-as-a-day-laborer/)

## To Reproduce
Steps to reproduce the behavior 
example: 
1. Go to [Find work as a day laborer](https://alpha.austin.gov/en/jobs/job-resources/help-finding-work/find-work-as-a-day-laborer/)
2. Scroll down to see big padding
3. See error

There's big padding on the map, and combined with the padding from basic steps it's *a lot*.
## Current behavior
I assume there's nothing to see after the basic steps

## Expected behavior
I want to see continuous content without anything hidden

## Screenshots
<kbd><img src= "https://images.zenhubusercontent.com/5d641145b9bd2f17c566338c/95f15339-9bc1-499f-b7b9-840211a7bbda" /></kbd>

**Comment by desigonz** [comment] 2019-11-26 14:51
Duplicate of #3028

**Closed by desigonz** 2019-11-26 14:51 UTC
Labels: Bug Reported, Content Type: Service Page
