### ISSUE TITLE
Joplin page field requirements implementation without preventing drafts

### ISSUE THREAD

**Issue by toribr** [cityofaustin/techstack#2180] opened 2019-05-29 14:04 UTC
### As an author, I need to be able to trust the system to let me know when I have not completed the field requirements for a page prior to publishing.

Currently Joplin only requires a title to publish. Before Joplin is used more broadly, the previously established requirements as outlined by the content model should be implemented, both from a system standpoint and from a visual design standpoint. 

Design work for this issue largely already exists, though there may be some refinement required, because current visual design does not match design in many other regards as well.

**Acceptance criteria—required for MVP**
SERVICE PAGE: In order to publish, required to have:
- [ ] Title
- [ ] Topic
- [ ] Description
- [ ] Steps
  - [ ] Content editors must add at least 2 steps
But in order to save, only require: 
- [ ] Title

INFORMATION PAGE: In order to publish, required to have:
- [ ] Title
- [ ] Description
But in order to save, only require: 
- [ ] Title

Additional context:
[Austin.gov content model](https://docs.google.com/spreadsheets/d/1ZkH93F4tJ0_Zjx4t8k6k6TgwSlOh8u8ejWmegE6WqH0/edit?usp=sharing)

**Comment by briaguya** [comment] 2019-06-07 12:54
Dev note: we need to look into how we can have a difference between "required to save draft" and "required to publish"

We don't want to implement this in a way that prevents people from saving their progress when they haven't figured out what to put in all the required fields yet.

**Comment by Niicck** [comment] 2019-06-11 18:57
List of fields required to publish are here: https://docs.google.com/spreadsheets/d/1ZkH93F4tJ0_Zjx4t8k6k6TgwSlOh8u8ejWmegE6WqH0/edit#gid=1131885431

**Comment by desigonz** [comment] 2019-09-05 22:14
dupe of #2767

**Closed by desigonz** 2019-09-05 22:14 UTC
Labels: Joplin 3.0, Team: Dev
