### ISSUE TITLE
Events list view: Janis

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#3817] opened 2020-01-23 00:01 UTC
### As a resident, I want to learn about events the City offers that are relevant to me, so that I can find one to attend.

- [ ] Design matches mocks
- [ ] Janis [spec overview ](https://xd.adobe.com/view/73b27c62-6b8e-4cb7-7d29-30bcdd886517-0583/)
- [ ] [Desktop](https://xd.adobe.com/view/73b27c62-6b8e-4cb7-7d29-30bcdd886517-0583/screen/5a90f9d0-253a-4275-9248-0cdae662b27c/Event-MVP-list-desktop-4)
  - [ ] [Mobile](https://xd.adobe.com/view/73b27c62-6b8e-4cb7-7d29-30bcdd886517-0583/screen/27ea2637-f07e-45e7-a434-20ff08138c5f/Event-MVP-list-mobile-2)
- [ ] Preview works for this content type
- [ ] Interactive states (hover, down, focus, keyboard focus, disabled)—Janis [spec overview ](https://xd.adobe.com/view/73b27c62-6b8e-4cb7-7d29-30bcdd886517-0583/)
- [ ] Defined behaviors: includes guidelines for layout (wrapping, truncation, overflow), animation, interactions, etc.—Janis [spec overview ](https://xd.adobe.com/view/73b27c62-6b8e-4cb7-7d29-30bcdd886517-0583/)

#### Test that the following content appears:
- [x] 10 events appear per page
  - [ ] Pagination kicks in once we have 11+ events
- [x] Events appear in chronological order, starting with today's date
- [x] For each event card, display:
  - [x] Date
    - [x] Date localizes; use the same translations we use for OPO. For days of the week, use [these translations](https://www.spanishdict.com/guide/days-of-the-week-in-spanish) and let's capitalize the first letter in each weekday
      - [x] `en`
      - [x] `es`
    - [x] In [mobile](https://xd.adobe.com/view/1b13a959-95b9-4c51-6936-1d77c5ff1be7-6d22/screen/068b4d0a-f96e-4308-9e2e-93a75c414bfe/Event-MVP-home-mobile), use shortened month and day of week
      - [x] English: `Jan` `Feb` `Mar` `Apr` `May` `Jun` `Jul` `Aug` `Sep` `Oct` `Nov` `Dec` /// `Sun` `Mon` `Tue` `Wed` `Thu` `Fri` `Sat`
      - [x] Spanish: `Ene` `Feb` `Mar` `Abr` `Mayo` `Jun` `Jul` `Ago` `Sep` `Oct` `Nov` `Dic` /// `Do` `Lu` `Ma` `Mi` `Ju` `Vi` `Sa`
  - [x] If canceled on Joplin, badge displays per mocks
  - [x] Title
    - [x] `en`
    - [x] `es`
  - [x] Display location title (no address)
  - [x] Cost
    - [x] If event is free, display `Free`
      - [x] `en`
      - [x] `es`: translate to `Gratis`
    - [x] If only one cost is entered into Joplin, display cost (ex. `$20`)
    - [x] If a multiple costs are entered into Joplin, display the range (ex. `$5–20`) and make sure it's an en dash separately that range, with no spaces :)
  - [x] Register/free and open to the public
    - [x] If there is a registration link in Joplin, display `Registration required` 
        - [x] `en`
        - [x] `es`: translate to `Registración requerido`
    - [ ] If there is no registration link in Joplin, display `Open to the public`
        - [ ] `en`
        - [ ] `es`: translate to `Abierto al público`
- [x] The entire event card links to the event detail page
- [x] No contextual nav

**Comment by easherma** [comment] 2020-01-23 04:08
Based on our dev design sync convo,
we’ll send all the events over to janis and then filter there, so we’ll need to implement a filter component there, which we ought to be able to design in such a way that we can reuse it for the homepage

**Comment by desigonz** [comment] 2020-01-27 15:24
@chiaberry updated events specs:
- [Overview](https://xd.adobe.com/view/73b27c62-6b8e-4cb7-7d29-30bcdd886517-0583/)
- List page: [desktop](https://xd.adobe.com/view/73b27c62-6b8e-4cb7-7d29-30bcdd886517-0583/screen/5a90f9d0-253a-4275-9248-0cdae662b27c/Event-MVP-List-Desktop)
- List page: https://xd.adobe.com/view/73b27c62-6b8e-4cb7-7d29-30bcdd886517-0583/screen/27ea2637-f07e-45e7-a434-20ff08138c5f/Event-MVP-List-Mobile

**Comment by desigonz** [comment] 2020-01-28 22:50
@chiaberry— @briaguya's been working on this: https://github.com/cityofaustin/janis/pull/678
I think that is the data side needed to get you started on this issue??

**Comment by chiaberry** [comment] 2020-02-13 21:57
@desigonz a few questions around the checklist above and the mocks
- [ ] Should we capitalize the first letter in the days of the weeks in Spanish?
- [ ] Moment.js is automatically adding a period after the abbreviations on mobile ex: `vie.` Is that okay? remove the periods?
- [ ] The checklist above says to include the word "Register" with no link, Chase's mocks say  Registration Required, or nothing at all if its open to the public. Follow the checklist?

If its easier I can deploy a wip so you can see what I have so far. Or post my questions to the content channel?

**Comment by desigonz** [comment] 2020-02-13 23:00
I added my answers above!

**Comment by chiaberry** [comment] 2020-02-19 03:29
ready to QA @desigonz and @chasechenevert 

https://janis-3817-event-lists.netlify.com/events/

the linked up joplin
http://joplin-pr-3817-event-lists.herokuapp.com/

I translated "Registration Required" as "Registracion Requerido", Desi, does that sound right?

**Comment by chiaberry** [comment] 2020-02-19 16:31
I moved some code out from the Official Documents (reusing the Pagination functions) so I'd appreciate some quick eyes on Official Documents to confirm no regression bugs.

**Comment by chasechenevert** [comment] 2020-02-19 20:00
@chiaberry excellent work! This is 99.99% there, the only thing I can see is:
- [ ] Event title: use the 500 (medium) weight

**Comment by desigonz** [comment] 2020-02-19 20:27
- [ ] Lowercase "required" in `Registration required`
![image](https://user-images.githubusercontent.com/5839508/74873013-f5bd3500-5323-11ea-9f3b-7821f4acc289.png)

**Comment by desigonz** [comment] 2020-02-19 20:33
Added one note about. @chasechenevert, can you confirm that the below has been dropped from the requirements? It's listed in acceptance criteria above but it's not in your mocks.
    - [ ] If there is no registration link in Joplin, display `Open to the public`
        - [ ] `en`
        - [ ] `es`: translate to `Abierto al público`

**Comment by chasechenevert** [comment] 2020-02-19 20:54
> Added two notes above. @chasechenevert, can you confirm that the below has been dropped from the requirements? It's listed in acceptance criteria above but it's not in your mocks.
> 
> * [ ]  If there is no registration link in Joplin, display `Open to the public`
>   
>   * [ ]  `en`
>   * [ ]  `es`: translate to `Abierto al público`

That's correct! We're not displaying "Open to the public" just yet. I connected with @toribr to check my memory as well and that's what she remembers too. It's something we might want to do in the future, but we haven't thought through it enough yet.

**Comment by chiaberry** [comment] 2020-02-21 15:21
@desigonz , I capitalized the months, lowercased required and fixed the weight of the event list.

Since I merged the joplin side of things, i had to switch over to staging which means I lost a lot of my test data, just FYI thats why the events are different

**Closed** 2020-02-27 17:06 UTC
Labels: Content Type:  Event, Janis Alpha, QA passed, Team: Dev
