### ISSUE TITLE
Design Process Page

### ISSUE THREAD

**Issue by LauraTrujillo** [cityofaustin/techstack#661] opened 2018-09-04 21:30 UTC
Refine existing designs utilizing [Permittingatx.com](https://permittingatx.com/) (sans overview page) for content. @toribr can explain further.

### Existing research and designs
- [Drive](https://drive.google.com/drive/u/1/folders/11TFsoMi4FgsJMGqscQ4pr-TZxRjYnoch)
- [V1 PDF](https://github.com/cityofaustin/techstack/files/2353944/alpha.austin.gov-processpage-v1.pdf)
- [V2 PDF](https://github.com/cityofaustin/techstack/files/2353944/alpha.austin.gov-processpage-v1.pdf)

### Examples from other gov sites
- [FOIA.gov information request](https://www.foia.gov/request/agency-component/d42a8692-bf5a-4d97-aeee-1389a96a9fba/)
- [WENYC How-To Guides](https://we.nyc/how-to-guides/)

**Comment by amenity** [comment] 2018-10-18 16:07
Duplicate of #808

**Closed by amenity** 2018-10-18 16:07 UTC
Labels: Content type: Process Page, Department: Development Services, Epic, Size: L, Team: Design + Research
