### ISSUE TITLE
Bug: fonts not displaying properly on IE

### ISSUE THREAD

**Issue by amenity** [cityofaustin/techstack#1266] opened 2019-02-21 14:39 UTC
**URL tested:** https://dxun9n0idyi09.cloudfront.net/police-oversight/complaint/introduction

Open [URL](https://live.browserstack.com/dashboard#os=Windows&os_version=10&browser=IE&browser_version=11.0&zoom_to_fit=true&full_screen=true&resolution=responsive-mode&url=https%3A%2F%2Fdxun9n0idyi09.cloudfront.net%2Fpolice-oversight%2Fcomplaint%2Fintroduction&speed=1&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://dxun9n0idyi09.cloudfront.net/police-oversight/complaint/introduction) on Browserstack

|Property | Value|
|------------ | -------------|
| Browser | Ie 11.0 |
| Operating System | Windows 10 |
| Resolution | 1440x788 |

**Screenshot Attached** 
[Screenshot URL](https://live.browserstack.com/issue-tracker/723327419cb1d3874169ee511c24af9e374afcaa/win10_ie_11.0.jpg)
 ![Screenshot URL](https://live.browserstack.com/issue-tracker/723327419cb1d3874169ee511c24af9e374afcaa/win10_ie_11.0.jpg)

**[Click here](https://live.browserstack.com/dashboard#os=Windows&os_version=10&browser=IE&browser_version=11.0&zoom_to_fit=true&full_screen=true&resolution=responsive-mode&url=https%3A%2F%2Fdxun9n0idyi09.cloudfront.net%2Fpolice-oversight%2Fcomplaint%2Fintroduction&speed=1&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://dxun9n0idyi09.cloudfront.net/police-oversight/complaint/introduction) to reproduce the issue on Browserstack**

**Comment by sergiogcx** [comment] 2019-02-21 17:42
I can confirm this happens in Microsoft Edge too, The link is there and it is functional. It is just the color that needs to be changed.

<img width="1440" alt="screen shot 2019-02-21 at 10 51 10 am" src="https://user-images.githubusercontent.com/5282430/53189638-9a9c1980-35cd-11e9-8ab6-2cd2902016c9.png">

**Comment by easherma** [comment] 2019-02-22 18:49
This may be due to the hacky way i threw together than menu bar; does there appear to be any other typography issues on the form?

**Comment by easherma** [comment] 2019-02-22 21:39
@sergiogcx @desigonz is this a dupe of https://github.com/cityofaustin/techstack/issues/1265 or are there other font issues I'm not noticing?

**Comment by desigonz** [comment] 2019-02-22 22:50
@easherma yes a dupe, and the fix looks good! closing this one.

**Closed by desigonz** 2019-02-22 22:50 UTC
Labels: Bug Reported, Department: Police Oversight, P3, Police Oversight Form
