### ISSUE TITLE
'More' button is not responsive

### ISSUE THREAD

**Issue by Jo-Dwyer** [cityofaustin/techstack#3561] opened 2019-12-09 20:53 UTC
## Describe the bug
Searched for a page, found a duplicate and chose to delete it. 'More' button won't respond.

https://joplin.herokuapp.com/admin/pages/search/?q=business%20resources

## To Reproduce
Steps to reproduce the behavior 
example: 
1. Go to 'Page'
2. Type in 'business resources'
3. Scroll down to find the dupe draft
4. Click more to delete
5. See error

## Current behavior
same as #3478 ..."Selecting the 'More' drop down under a page in Joplin search doesn't do anything."

## Expected behavior
Expected teh dropdown to appear with option to unpublish, delete, etc.

## Screenshots
![bug_no more.gif](https://images.zenhubusercontent.com/5d641145b9bd2f17c566338c/b19cfd8f-5205-4b64-b4e8-7752f63ad86c)

**Comment by chiaberry** [comment] 2020-01-08 17:04
I had this happen to me when I was working on the permissions issue, but I didnt notice anything consistent about when it would happen. I tried right now to replicate it and I can't. But it definitely happens. I'll keep an eye out for it while Im working on stuff in joplin.

**Comment by desigonz** [comment] 2020-01-09 15:56
I wonder if this is related to #3515?

**Comment by Jo-Dwyer** [comment] 2020-01-09 17:26
@desigonz re: #3515 I'm not sure. The non-functional "More" button isn't dependent upon a null yield in the search field. For example, I just looked up the search term "mobile", selected more, and got no response, whereas in #3515 the "Create new" non-functionality behaves as though it is dependent on a null search yield.

**Comment by chiaberry** [comment] 2020-01-09 17:36
Aha!! If you use the search at all and then try to click more it doesnt work. refresh the page and more works.

**Comment by easherma** [comment] 2020-01-10 00:21
This is a bug in wagtail, it happens even in wagtail-bakery. 

I think the problem is in:
https://github.com/wagtail/wagtail/blob/master/wagtail/admin/static_src/wagtailadmin/js/core.js

Search is being triggered even when you click the dropdown on a page listing, I think.

**Comment by easherma** [comment] 2020-01-10 03:11
I fixed this via a PR to wagtail! 

https://github.com/wagtail/wagtail/pull/5759

Lets touch base about how to follow this through our QA and release process. 

You can test it here: 
https://eashermamaster-oatna.squash.io/admin/

admin is admin, PW is 'changeme'

If you search and then click the dropdown, it works.

**Comment by desigonz** [comment] 2020-01-10 16:07
Looks good on https://eashermamaster-oatna.squash.io/admin/. What are you thinking for merging this into our own instance of Wagtail? I'm guessing it should get merged into a branch and then we follow QA for this issue as usual.

**Comment by easherma** [comment] 2020-01-10 16:39
We don't currently have a fork of Wagtail setup, we could do set one up or just know the fix is there and coming in a future version. It might take a few days too for the team to respond to my PR and have a better sense of what version it might make it into. We'll discuss at dev sync.

**Comment by easherma** [comment] 2020-01-17 18:30
@desigonz made it into Wagtail 2.8!
https://github.com/wagtail/wagtail/commit/f5f841ed5992d63c5c6f5b0ee0a56c7b75ca0cb9

**Comment by desigonz** [comment] 2020-02-14 20:33
👍 Looks great in this Wagtail 2.8 PR branch https://joplin-pr-3912-wagtail-28.herokuapp.com/admin/pages/search/

**Closed** 2020-03-04 21:33 UTC
Labels: Bug Reported, Joplin Alpha, P4, Team: Dev
