### ISSUE TITLE
User Story: As a resident, I want to understand the data collected by the City when I visit the website to make sure my privacy is maintained.

### ISSUE THREAD

**Issue by mateoclarke** [cityofaustin/techstack#252] opened 2018-04-09 14:58 UTC
@ashleecoa commented on [Fri Feb 09 2018](https://github.com/cityofaustin/janis/issues/135)

We need to write and add a privacy policy to alpha. Here's the austintexas.gov one: http://austintexas.gov/page/privacy-policy

Should we consult with Law Department? 

See also https://github.com/cityofaustin/techstack/issues/173

---

@LauraTrujillo commented on [Tue Feb 13 2018](https://github.com/cityofaustin/janis/issues/135#issuecomment-365296786)

Instead of re-writing this existing privacy policy, we just need to create a page for it on alpha.austin.gov

**Comment by amenity** [comment] 2018-04-10 02:52
Duplicate of #251

**Closed by amenity** 2018-04-10 02:52 UTC
