### ISSUE TITLE
"Work in progress" messaging on IA pages

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#3992] opened 2020-02-19 23:09 UTC
### As a user who is looking for City content and lands on alpha.austin.gov IA pages, I want clear messaging saying that the website is a work in progress/not all content will be available, so that I know where to go to find the information I need right now.

Via the austin.gov feedback box, we received this feedback from someone on the [Business permits and licenses](https://alpha.austin.gov/en/permits-tickets/business-permits-and-licenses/) topic collection:
> The link to Business permits and licenses only shows Food business permits and has no links to anything else. ([source](https://github.com/cityofaustin/alpha-feedback/issues/162))

Just as we message that alpha is a work in progress on the global nav, we might want to do the same on IA pages, in case that's where a user lands.

# Design
Abstract branch: https://share.goabstract.com/31611ec1-8b14-498c-b231-ad5448976935
- [x] Reviewed with Tori
- [ ] Merge

**Comment by toribr** [comment] 2020-05-15 13:56
Since we have new messaging in the nav bar and also on search, it makes sense to add it to topics as well so that we have full coverage.

**Comment by chase-vert** [comment] 2020-05-15 15:45
Based on Design planning, this message will be inserted onto every page on the site.

**Comment by toribr** [comment] 2020-05-18 13:53
Here's the page it will link to: https://alpha.austin.gov/a-new-website-for-the-city-of-austin/

**Comment by chase-vert** [comment] 2020-05-18 15:01
Just want to confirm with content that this is still the message, 
- Currently live: "[Visit austintexas.gov for the current city website.](https://austintexas.gov/) [Help us improve our website.](https://alpha.austin.gov/en/feedback/)"
- GlobalNav v2 [pre-implementation] "This site is a work in progress. Visit [austintexas.gov](http://austintexas.gov/) for the full city website."

Is this still correct, and where should the new "about" page be linked? @Jo-Dwyer

**Comment by chase-vert** [comment] 2020-06-12 20:07
To-do
- [ ] Tablet
- [ ] Mobile

**Comment by chase-vert** [comment] 2020-06-25 20:02
Switched this over to dev

**Comment by toribr** [comment] 2020-06-29 14:55
Given that anyone that uses search will likely turn up a null result, it seems like we need a "WIP" message for the null results page. Will write a separate issue.

**Comment by jairPineros** [comment] 2020-08-12 21:31
The Message is present and quite obvious very hard to miss. So hard to miss that it is border line distracting... maybe we could add an option to close the message? @toribr @chase-vert @robbobfrh84

**Comment by toribr** [comment] 2020-08-13 12:54
@jairPineros Working as designed. :) 

I'll need to see complaints from the residents before I'll consider changes.

**Comment by toribr** [comment] 2020-08-13 14:02
@jairPineros Also, residents visit about 1.5 pages per YEAR.

**Comment by jairPineros** [comment] 2020-08-13 14:20
@toribr sounds good

**Closed** 2020-08-20 20:25 UTC
Labels: Content type: Topic Page, Content type: Topic collection page, Feature: Search, Janis Alpha, QA passed, Team: Dev
