### ISSUE TITLE
Add error messaging to content creation modals

### ISSUE THREAD

**Issue by toribr** [cityofaustin/techstack#745] opened 2018-09-21 18:33 UTC
**Describe the bug**
No error messaging on empty required fields

**To Reproduce**
1. Go to Create Content
2. Click on service page
3. Enter no characters in the page title field
or
1. create content
2. enter page title
3. make no selection of topic

**Current behavior**
After above steps, User cannot proceed (button disabled), but no error message is presented.

**Expected behavior**
System should display message indicating how to proceed.

**Screenshots**
![screen shot 2018-09-21 at 1 28 49 pm](https://user-images.githubusercontent.com/3790067/45899576-d888dd80-bda2-11e8-9f3d-cdbd3d31650f.png)

![screen shot 2018-09-21 at 1 39 25 pm](https://user-images.githubusercontent.com/3790067/45899960-eab74b80-bda3-11e8-91c5-74dd5eddbbdd.png)

**Comment by desigonz** [comment] 2019-08-28 22:01
Duplicate of #2612, which is now in production!

**Closed by desigonz** 2019-08-28 22:01 UTC
Labels: Author Interface, Feature: Create Content Modal, Joplin Alpha, Size: M, Team: Dev, Wagtail
