### ISSUE TITLE
Plan + Draft brownfields information page 

### ISSUE THREAD

**Issue by annieszot** [cityofaustin/techstack#2158] opened 2019-05-28 22:36 UTC

**Comment by annieszot** [comment] 2019-05-29 02:31
See #1112 
- [ ]  IA linked (draft)
- [ ] Governance/Workflow #1971 
- [ ] Draft

**Comment by annieszot** [comment] 2019-06-13 16:29
Assigning to @LauraTrujillo

**Comment by LauraTrujillo** [comment] 2019-06-17 15:13
This is a duplicate of #1122, so I'm going to close it.

**Closed by LauraTrujillo** 2019-06-17 15:13 UTC
Labels: Content Type: Information Page, Department: Resource Recovery, Team: Content
