### ISSUE TITLE
UI on new service page should match UI on edit service page

### ISSUE THREAD

**Issue by toribr** [cityofaustin/techstack#702] opened 2018-09-14 13:14 UTC
**Describe the bug**

**Details**
  - URL:
  - Device: _E.g. desktop/laptop, tablet, or phone_
  - Browser: _Use [browser info](https://www.whatismybrowser.com/) if you are unsure_ 

**Current behavior**
A clear and concise description of what happened.

**Expected behavior**

**To Reproduce**

**Screenshots**
If applicable, add screenshots or a gif to help explain your problem.

**Additional context**
Add any other context about the problem here. Does this prevent a user from completing a task? If so, what task?

**Comment by amenity** [comment] 2018-09-18 02:59
duplicate of #686

**Closed by amenity** 2018-09-18 02:59 UTC
