### ISSUE TITLE
Implement Top Services in Janis

### ISSUE THREAD

**Issue by amenity** [cityofaustin/techstack#1399] opened 2019-03-05 19:44 UTC

**Comment by pibemillo** [comment] 2019-04-11 17:28
This is a duplicate of https://github.com/cityofaustin/techstack/issues/1636.

There is a PR out for this https://github.com/cityofaustin/janis/pull/354

Preview link: https://janis-staging-pr-354.herokuapp.com/police-oversight

**Closed** 2019-04-25 02:38 UTC
Labels: Janis 2.0, Resident Interface, Team: Dev
