### ISSUE TITLE
Publisherr (Publisher thinks there isn't a netlify app for PR but there is)

### ISSUE THREAD

**Issue by easherma** [cityofaustin/techstack#3956] opened 2020-02-12 18:50 UTC
## Describe the bug
For https://github.com/cityofaustin/techstack/issues/3852 , we ran into a publishing error when setting up https://github.com/cityofaustin/janis/pull/689 to be published by https://github.com/cityofaustin/joplin/pull/555 . 

As you can see here, from when we tried to trigger a publish from the joplin PR app:
https://console.aws.amazon.com/cloudwatch/home?region=us-east-1#logEventViewer:group=/aws/lambda/coa-publisher-mvp-pr;stream=2020/02/11/[$LATEST]713556b0b05d467198be25af6fb1ed83;start=2020-02-10T17:31:17Z

## To Reproduce
Reproducing this as is would be more labor intensive, since that PR branch has been merged the app does not exist and it's JanisBranchSettings are lost. I made an issue to address this: https://github.com/cityofaustin/techstack/issues/3954

These aren't proven to have caused the bug, but some potential factors:
* I set the CMS API variable in netlify to match the Joplin PR:
https://app.netlify.com/sites/janis-3567-richtext-links/settings/deploys#environment
 I'm not sure how these could have caused the error, but perhaps it could have affected the way Publisher parses through existing sites or something similar. Since the signal did successfully trigger a build, I'm more inclined to think it is a bug with Publisher than with Joplin. 

* In JanisBranchSettings, I had the preview input set to URL, and had the correct URL. I wouldn't expect this to affect the publish branch name setting, though

Steps to reproduce the behavior (potentially)
example: 
1. Make a Joplin app
2. Set up JanisBranchSettings to point to a Janis branch
3. Update a page or otherwise trigger a publish
4. Check if the Netlify app deploys or not

## Current behavior
No netlify build triggered, see CloudWatch error

## Expected behavior
A successful publish

## Screenshots
![image](https://user-images.githubusercontent.com/10539855/74367053-d019b400-4d96-11ea-927c-add7d19dc21c.png)

![image](https://user-images.githubusercontent.com/10539855/74367480-91382e00-4d97-11ea-8e35-8da5b9792307.png)

I would screenshot the JanisBranchSettings, but they no longer exist. 

## Additional context

This will make testing changes on PRs for QA more difficult if we can't reliably select a Janis branch or otherwise know why something is going wrong.

**Comment by Niicck** [comment] 2020-02-12 19:43
Let's take a look at this when it happens again, since we have no way to reproduce it and the build function has been working for other branches.

Setting the env variable of "DELETION_PROTECTION"="1" will preserve your heroku instance even after merging in Joplin code. So we can debug even if the branch still has to be merged in.
https://github.com/cityofaustin/coa-joplin-clean-up#wait-i-dont-want-you-to-automatically-delete-my-app

We can manually inspect the "get_site()" function and see what went wrong. https://github.com/cityofaustin/publisher/blob/master/src/coa-publisher-mvp/src/helpers/netlify.py Maybe request pagination isn't working. Maybe the PR app hadn't been built yet at the time of the publish request.

**Closed** 2020-10-28 16:06 UTC
Labels: Bug Reported, Team: Dev
