### ISSUE TITLE
Global Nav -- Add to Janis

### ISSUE THREAD

**Issue by ifsimicoded** [cityofaustin/techstack#106] opened 2018-02-23 06:45 UTC
Use this sketch file, referencing only homepage and navigation: https://drive.google.com/open?id=1wtiU9LqpvU2KTu362bCPMfS7tfYgjyuf

- [x] add theme level navigation

- [x] Show the themes. If the topics aren't yet active, make the theme text gray on hover and only show a "wip" message in the sublist body. If there are active topics, make the theme text orange, only show the active sublist items, and show the "wip" message.

- [x] add airport icon to tablet and desktop header, and in mobile menu- links to http://austintexas.gov/department/airport

- [x] add 311 link to header to tablet and desktop, and in mobile menu- links to http://311.austintexas.gov/reports/list_services

- [x] add 'alpha' to 'austin.gov' = 'alpha.austin.gov'

![alpha_l_0 0_home_menua](https://user-images.githubusercontent.com/20911665/36875237-c4a0cb80-1d74-11e8-9f28-3fa65e3c27f6.png)
![alpha_m_0 0_home_menu](https://user-images.githubusercontent.com/20911665/36875238-c4b9291e-1d74-11e8-906f-01201c09d371.png)
![alpha_s_0 0_home_menu_expand](https://user-images.githubusercontent.com/20911665/36875239-c4cff3e2-1d74-11e8-845b-2a2b242de8b1.png)
![alpha_s_0 0_home_menu](https://user-images.githubusercontent.com/20911665/36875240-c4ea8662-1d74-11e8-8ae0-c6958ccec6d1.png)

#### Behaves like: https://www.mass.gov/

**Comment by mateoclarke** [comment] 2018-02-27 21:53
This is a duplicate of cityofaustin/janis#124

**Comment by mateoclarke** [comment] 2018-03-12 22:57
This is now is master with PR https://github.com/cityofaustin/janis/pull/160 being merged.

More iteration will be in https://github.com/cityofaustin/janis/pull/167

And more design iterations are expecting in dev/design review on 3/12

**Closed by mateoclarke** 2018-03-12 22:57 UTC
Labels: Feature: Global Nav, Short Term, Size: M, Team: Dev
