### ISSUE TITLE
Change "evidence" to "media" on "Share your photos or video" page of complaint form 

### ISSUE THREAD

**Issue by srigdon** [cityofaustin/techstack#1578] opened 2019-03-22 22:02 UTC
![Screen Shot 2019-03-22 at 4.53.00 PM.png](https://images.zenhubusercontent.com/5be0b7bea977220c77bd229b/34a656c7-c610-4a99-b03e-ad98fecf7d00)

In case it matters, I'm using Version 72.0.3626.121 of Chrome on a Macbook Air.

**Comment by oliver2g** [comment] 2019-03-25 17:59
duplicate of #1576

**Closed by oliver2g** 2019-03-25 17:59 UTC
Labels: Police Oversight Form, Team: Dev
