### ISSUE TITLE
lowercase all the AMs and PMs

### ISSUE THREAD

**Issue by amenity** [cityofaustin/techstack#1345] opened 2019-02-27 02:13 UTC
Lower priority—our style is to lowercase am and pm.  

**URL tested:** https://alpha.austin.gov/en/police-oversight

Open [URL](https://live.browserstack.com/dashboard#os=android&os_version=8.0&device=Samsung+Galaxy+S9+Plus&device_browser=chrome&zoom_to_fit=true&full_screen=true&url=https%3A%2F%2Falpha.austin.gov%2Fen%2Fpolice-oversight&speed=1&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://alpha.austin.gov/en/police-oversight) on Browserstack

|Property | Value|
|------------ | -------------|
| Device | Samsung Galaxy S9 Plus |
| Browser | Mobile_chrome |
| Operating System | Android 8.0 |
| Resolution | 1440 x 2960 px |
| Screen size | 6.2 in - 6.2 x 2.9 in |
| Viewport | 360 x 740 dp |
| Aspect Ratio | 18.5 : 9 |

**Screenshot Attached** 
[Screenshot URL](https://live.browserstack.com/issue-tracker/51a8b797af7003c66fe285a2407d6cc0c2fdec49/realdroid_Samsung_Galaxy_S9_Plus.jpg)
 ![Screenshot URL](https://live.browserstack.com/issue-tracker/51a8b797af7003c66fe285a2407d6cc0c2fdec49/realdroid_Samsung_Galaxy_S9_Plus.jpg)

**[Click here](https://live.browserstack.com/dashboard#os=android&os_version=8.0&device=Samsung+Galaxy+S9+Plus&device_browser=chrome&zoom_to_fit=true&full_screen=true&url=https%3A%2F%2Falpha.austin.gov%2Fen%2Fpolice-oversight&speed=1&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://alpha.austin.gov/en/police-oversight) to reproduce the issue on Browserstack**

**Comment by Niicck** [comment] 2019-03-21 20:23
Duplicate of https://github.com/cityofaustin/techstack/issues/1511

**Closed by Niicck** 2019-03-21 20:23 UTC
Labels: Bug Reported, Department: Police Oversight, P4, Team: Dev
