### ISSUE TITLE
"More" button doesn't work after entering data in search

### ISSUE THREAD

**Issue by Niicck** [cityofaustin/techstack#3844] opened 2020-01-25 21:10 UTC
## Describe the bug
When you search for a page, the "more" button stops working

## To Reproduce
Steps to reproduce the behavior 
example: 
1. Enter something in the search bar
2. Click on "more"
3. Nothing happens

## Screenshots

![Screen Shot 2020-01-25 at 3.08.23 PM.png](https://images.zenhubusercontent.com/5b9fcb6c68df0477b25368b3/08799e1e-3862-4477-a536-6f46e5a1fcbe)

## Device and browser
Chrome, locally.

**Comment by Niicck** [comment] 2020-01-28 00:16
jk duplicate of #3561

**Comment by chiaberry** [comment] 2020-01-28 18:45
will this be fixed once they release and we upgrade to wagtail 2.8?

**Comment by desigonz** [comment] 2020-01-30 00:15
Yep, duplicate of #3561 which will be merged in with 2.8.

**Closed by desigonz** 2020-01-30 00:15 UTC
Labels: Bug Reported, Joplin Alpha, Team: Dev
