### ISSUE TITLE
Process Page Content

### ISSUE THREAD

**Issue by ifsimicoded** [cityofaustin/techstack#475] opened 2018-06-29 19:24 UTC
Finalize Process Page Content that I believe is close to done so it can be added to the Alpha site. (still being added via yaml files). Let me know if you need the structure of the Process data model to do this.
- [ ] Foster Content
- [ ] EMS Content

**Comment by amenity** [comment] 2018-07-12 16:05
FWIW, we can't put up the Foster page until we have a form.

**Comment by ashleecoa** [comment] 2018-08-23 16:13
I recommend content around Food Manager
http://austintexas.gov/department/food-personnel-requirements
http://austintexas.gov/online-form/food-manager-certificates

**Comment by amenity** [comment] 2018-10-03 18:10
Duplicate of #773

**Closed by amenity** 2018-10-03 18:10 UTC
Labels: Content type: Process Page, Department: Animal Center, Department: EMS, Foster Application, Team: Content
