### ISSUE TITLE
Missing alt text for Farah's image

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#1326] opened 2019-02-26 22:01 UTC
**URL**
https://alpha.austin.gov/police-oversight
https://alpha.austin.gov/es/police-oversight

**Screenshots**
![image.png](https://images.zenhubusercontent.com/5a31a50b8a75884b908b0ea6/5b533cb7-39b6-4431-b36f-6e3d96e92eb7)

**Comment by amenity** [comment] 2019-02-26 22:58
Duplicate of #1314.

**Closed by amenity** 2019-02-26 22:58 UTC
Labels: Bug Reported, Department: Police Oversight, Police Oversight Form, a11y
