### ISSUE TITLE
Get ARR department page approved

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#2716] opened 2019-08-08 22:18 UTC
Preview: https://alpha.austin.gov/en/preview/department/UGFnZVJldmlzaW9uTm9kZToxMTc3
Shared/approval requested 8/19/19

**Comment by annieszot** [comment] 2019-08-21 19:32
Blocker at ARR - approver is OOO. Moving to sprint 38

**Comment by annieszot** [comment] 2019-09-04 15:31
Issue is duplicate of #2141 Closing.

**Closed by annieszot** 2019-09-04 15:31 UTC
Labels: Content Type: Department Page, Department: Resource Recovery, Site Content, Team: Content
