### ISSUE TITLE
Service tiles aren't centered in IE11

### ISSUE THREAD

**Issue by oliver2g** [cityofaustin/techstack#2088] opened 2019-05-22 22:51 UTC
On the OPO dept page, the tiles are too low on the page and get cut off

**URL tested:** https://janis.austintexas.io/en/departments/

Open [URL](https://live.browserstack.com/dashboard#os=Windows&os_version=10&browser=IE&browser_version=11.0&zoom_to_fit=true&full_screen=true&resolution=responsive-mode&url=https%3A%2F%2Fjanis.austintexas.io%2Fen%2Fdepartments%2F&speed=1&host_ports=google.com%2C80%2C0&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://janis.austintexas.io/en/departments/) on Browserstack

|Property | Value|
|------------ | -------------|
| Browser | Ie 11.0 |
| Operating System | Windows 10 |
| Resolution | 1440x788 |

**Screenshot Attached** 
[Screenshot URL](https://live.browserstack.com/issue-tracker/5763af433d8b9ba95c777e8fa7f64b977558edc1/win10_ie_11.0.jpg)
 ![Screenshot URL](https://live.browserstack.com/issue-tracker/5763af433d8b9ba95c777e8fa7f64b977558edc1/win10_ie_11.0.jpg)

**[Click here](https://live.browserstack.com/dashboard#os=Windows&os_version=10&browser=IE&browser_version=11.0&zoom_to_fit=true&full_screen=true&resolution=responsive-mode&url=https%3A%2F%2Fjanis.austintexas.io%2Fen%2Fdepartments%2F&speed=1&host_ports=google.com%2C80%2C0&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://janis.austintexas.io/en/departments/) to reproduce the issue on Browserstack**

**Comment by briaguya** [comment] 2019-05-23 17:22
It looks like the real issue here is the broken centering, I can address that but I'm pretty sure the "too low" part of the issue is as designed (not any different than in chrome etc.)

@toribr @chasechenevert any input?

**Comment by briaguya** [comment] 2019-05-23 20:04
Renaming issue to be about centering as the rest is covered by https://github.com/cityofaustin/techstack/issues/2097

**Comment by sergiogcx** [comment] 2019-05-24 03:08
It looks like the reason it works in the index page and not in the department page is the "!important" directive in the stylesheets. Will make sure I implement these in the department page in #2097.

![Screen Shot 2019-05-23 at 10.03.17 PM.png](https://images.zenhubusercontent.com/5b7edad7290aac725aec290c/9d381bfe-3661-40bf-902c-b4bb557d13cf)

**Comment by sergiogcx** [comment] 2019-05-24 10:38
This gets resolved in PR:

https://github.com/cityofaustin/janis/pull/422

https://janis-pr.austintexas.io/422/



Issues fixed by this branch:

https://app.zenhub.com/workspaces/office-of-design-and-delivery-5a78b88e1ce69f3510b678ef/issues/cityofaustin/techstack/2097
https://app.zenhub.com/workspaces/office-of-design-and-delivery-5a78b88e1ce69f3510b678ef/issues/cityofaustin/techstack/2088
https://app.zenhub.com/workspaces/office-of-design-and-delivery-5a78b88e1ce69f3510b678ef/issues/cityofaustin/techstack/2011
https://app.zenhub.com/workspaces/office-of-design-and-delivery-5a78b88e1ce69f3510b678ef/issues/cityofaustin/techstack/2084
https://app.zenhub.com/workspaces/office-of-design-and-delivery-5a78b88e1ce69f3510b678ef/issues/cityofaustin/techstack/2009

**Comment by briaguya** [comment] 2019-05-24 10:48
Homepage changes are looking kinda wonky on mobile
![May-24-2019 05-47-49](https://user-images.githubusercontent.com/6384156/58322753-81328580-7de7-11e9-80c3-a51425ea839d.gif)

**Closed** 2019-05-30 00:25 UTC
Labels: Bug Reported, Janis Alpha, Team: Dev
