### ISSUE TITLE
Janis GraphQL test to Joplin CI

### ISSUE THREAD

**Issue by ifsimicoded** [cityofaustin/techstack#733] opened 2018-09-19 20:22 UTC
This will check to ensure our migrations, code changes in Joplin and database changes are operable in the Janis app.

**Comment by easherma** [comment] 2019-05-13 18:54
This seems like a dupe of https://github.com/cityofaustin/techstack/issues/1658, what do you think? @sergiogcx ?

**Closed** 2019-09-10 20:31 UTC
Labels: DevOps, Team: Dev
