### ISSUE TITLE
official document isn't publishing successfully

### ISSUE THREAD

**Issue by Jo-Dwyer** [cityofaustin/techstack#4421] opened 2020-05-20 19:37 UTC
## Describe the bug
Mia Demers is trying to publish a new document. She published one at 1:48pm. She immediately scrolled back down to the bottom of the official doc page and it was still there. She logged out and just checked the website, it hasn't popped up and it's been 30 mins. SHe logged back into joplin and scrolled to bottom and it was gone... 

## URL
[page in joplin](https://joplin.herokuapp.com/admin/pages/203/edit/#tab-content)
[page live](https://alpha.austin.gov/en/police-oversight/official-complaint-and-discipline-documents/#1)
['Formal complaint: Purpose and scope and other policy violations 2020-0368' should be published on that page per Mia](https://joplin.herokuapp.com/admin/documents/edit/357/)

## Current behavior
the page is not published live

## Expected behavior
publish the page and the page goes live

## Screenshot
Superweird, because it's showing up in revision history and at the very bottom of the editor now but not on the live page.
![Screen Shot 2020-05-20 at 5.22.37 PM.png](https://images.zenhubusercontent.com/5d641145b9bd2f17c566338c/03b863bf-0c57-4fc5-9db6-c6e0b8a450e2)

## Device and browser
 ~Microsoft Edge~ Firefox, Dell laptop running windows

## Additional context
This isn't the first time a published page hasn't published for Mia and it is blocking our attempts to successfully onboard them as publishers of their own content.

**Comment by chiaberry** [comment] 2020-06-22 16:11
I believe this issue was due to moderator/publisher permissions not working as intended. Closing issue for now, but reopen if it reoccurs.

**Closed by chiaberry** 2020-06-22 16:11 UTC
Labels: Bug Reported, Content type: Official document
