### ISSUE TITLE
Police Oversight form: Update email addresses

### ISSUE THREAD

**Issue by amenity** [cityofaustin/techstack#1231] opened 2019-02-19 16:43 UTC
The confirmation emails should be updated to have the following email addresses:
- Sender: noreply@atxpoliceoversight.org
- Reply-to: policeoversight@austintexas.gov

**Comment by sergiogcx** [comment] 2019-02-19 17:48
So yes, I can definitely do this very quickly, all I have to do is change two text fields in AWS. 

As soon as I change them in AWS the form will be submitting data to OPO/APD.

Best if we plan ahead of this?

**Comment by sergiogcx** [comment] 2019-02-20 18:44
So I have created a branch to make this happen; also, I set up the 

** HOWEVER, the email address `policeoversight@austintexas.gov` will need to be confirmed in AWS; meaning we will have to send them a confirmation email and they will need to accept the invitation.

@amenity

**Comment by sergiogcx** [comment] 2019-02-20 18:59
Here is the PR branch:

https://github.com/cityofaustin/form-service-api/pull/7

**Comment by sergiogcx** [comment] 2019-02-20 20:03
I have sent the email to `policeoversight@austintexas.gov`, the title in the email is `Amazon Web Services – Email Address Verification Request in region US East (N. Virginia)`, and the email looks like this:

![Screen Shot 2019-02-20 at 2.02.18 PM.png](https://images.zenhubusercontent.com/5b7edad7290aac725aec290c/293816cc-7c76-40a0-b9fb-fd1465c5a5a6)

**Comment by sergiogcx** [comment] 2019-02-20 23:57
I needed another PR to fix Zappa's environment variables. They are not set up automatically.

**Comment by sergiogcx** [comment] 2019-02-21 00:00
Okay, this should do it: https://github.com/cityofaustin/form-service-api/pull/8/files

Testing as we speak.

**Comment by sergiogcx** [comment] 2019-02-21 00:10
Tested and working! Merged to master.

**Comment by sergiogcx** [comment] 2019-02-21 01:13
Resized to M, it took two days to complete.

**Closed** 2019-02-25 22:23 UTC
Labels: Department: Police Oversight, Feature: Forms, Police Oversight Form, Size: M, Team: Dev
