### ISSUE TITLE
Draft informational page for Austin Healthy Adolescent programs

### ISSUE THREAD

**Issue by LauraTrujillo** [cityofaustin/techstack#570] opened 2018-07-31 22:14 UTC
http://austintexas.gov/department/healthy-adolescent

find how people sign up

Aha! Link: https://desi1.aha.io/features/RT-263

**Comment by desigonz** [comment] 2019-03-11 17:13
duplicate of #1159

**Closed by desigonz** 2019-03-11 17:13 UTC
Labels: Department: Public Health, Site Content, Size: S, Team: Content
