### ISSUE TITLE
Import service page steps with locations

### ISSUE THREAD

**Issue by briaguya** [cityofaustin/techstack#4280] opened 2020-04-15 16:38 UTC
we're skipping them at the moment

starting trying things out here https://github.com/cityofaustin/joplin/pull/692

need to investigate/diagnose/address https://github.com/cityofaustin/janis/pull/736/files#diff-01d9907d37c79bb548553a5a687ebc9bR122

**Comment by Niicck** [comment] 2020-04-17 15:57
Duplicate of techstack/4275

**Closed by Niicck** 2020-04-17 15:57 UTC
Labels: Janis Alpha, Joplin 3.0, Team: Dev
