### ISSUE TITLE
Identify general-use banner image photos

### ISSUE THREAD

**Issue by amenity** [cityofaustin/techstack#637] opened 2018-08-23 16:06 UTC
Need to identify a handful of high-quality-yet-generic photos to use as banner images.

Free stock images that are pretty good quality: https://unsplash.com/search/photos/austin
Good one here: https://unsplash.com/photos/HCcmfL-l08I

**Comment by amenity** [comment] 2018-08-23 18:58
cc @chasechenevert @toribr @courtneyjacinic @ashleecoa @LauraTrujillo

**Comment by LauraTrujillo** [comment] 2018-08-23 19:40
Duplicate of issue #630

**Comment by chasechenevert** [comment] 2018-08-23 19:47
Is there any specific place where I should handoff these assets (I'm not within Google Drive yet since I don't have a city email address).

**Comment by toribr** [comment] 2018-08-23 19:49
They need to go on google drive – so hang on to them until that happens? (unless it takes forever, and then we’ll figure something else out)

**Comment by chasechenevert** [comment] 2018-08-27 15:41
cc: @toribr @courtneyjacinic @ashleecoa @LauraTrujillo

I went through austin.gov to get some ideas for general buckets to put images into--the content team will likely have some better ideas about how they want to organize this, but this should be a starting point. I'll also populate a spreadsheet with metadata for each image, just in case that info needs to be accessed in the future. 

- Drive folder: https://drive.google.com/drive/folders/1IOMwkZxgWPpT6Sr5p4quuJB-2qkS5aoo?usp=sharing
- Asset inventory Google Sheet: https://docs.google.com/spreadsheets/d/1jnSGqSBAfLaVCvwQmgzl5Apw5YlsNI2kWWKqIq135xY/edit?usp=sharing

I'll be populating this folder across the sprint, as well as focusing on health related images for #630.

**Comment by chasechenevert** [comment] 2018-09-04 16:26
Same with #630 I'm closing this out since the pool of images is a nice size. I'll continue to add as we move along, and as needs arise. Just as a note, I've exclusively used [unsplash.com](https://unsplash.com/) so if you're looking to add more I recommend checking it out.

**Closed by chasechenevert** 2018-09-04 16:26 UTC
Labels: Site Content, Size: S, Team: Design + Research
