### ISSUE TITLE
ODD service offerings one-pager

### ISSUE THREAD

**Issue by chasechenevert** [cityofaustin/techstack#2653] opened 2019-07-26 17:25 UTC
- Nameir asked for some help with designing one-pager to promote ODD's service offerings. He's going to connect with me next week with the content.
- [Draft 1 content](https://docs.google.com/document/d/1nBdE4PJ52jQi9tFgfxvxZjyeF_DwkP0FvgxnkEncIK8/edit) is now in

**Comment by chasechenevert** [comment] 2019-08-26 13:57
Status update: waiting for content to be developed.

**Comment by desigonz** [comment] 2019-09-05 21:18
dupe of #2913

**Closed by desigonz** 2019-09-05 21:18 UTC
Labels: Project Communication
