### ISSUE TITLE
Food Truck Permit Guide content blocks are not behaving as expected on mobile.

### ISSUE THREAD

**Issue by kriskristin** [cityofaustin/techstack#3228] opened 2019-10-21 19:39 UTC
**Describe the bug**
Content sections on the guide are overflowing in mobile

**URL**

**To Reproduce**

1. Go to [the guide](http://janis-austin-gov-staging.s3-website-us-east-1.amazonaws.com/en/health-safety/healthcare-prevention/disease-prevention/mobile-food-vendor-permit-guide/#Maintain-or-renew-your-permit-1)

2. Scroll down to 'contact information'
3. See error

**Current behavior**
Content blocks are overflowing off the screen

**Expected behavior**
Content blocks should be contained within the mobile window.

**Screenshots**
![IMG_6A7616E5A0D2-1](https://user-images.githubusercontent.com/12438022/67237251-86384700-f410-11e9-83b4-d5a2ea0ae002.jpeg)

**Device**
iPhone X

**Browser**
Firefox and Chrome

**Comment by desigonz** [comment] 2019-10-28 14:53
duplicate of #3165

**Closed by desigonz** 2019-10-28 14:53 UTC
Labels: Content Type: Guides, Team: Dev
