### ISSUE TITLE
Thumbnails don't preview

### ISSUE THREAD

**Issue by toribr** [cityofaustin/techstack#697] opened 2018-09-13 16:48 UTC
**Describe the bug**
Thumbnails within edit mode and within image gallery are not previewing correctly but show broken link. However, newly uploaded images do upload and preview.
![screen shot 2018-09-12 at 11 52 17 am](https://user-images.githubusercontent.com/3790067/45502906-dbeceb00-b74a-11e8-8d44-12d4300b22eb.png)

**Comment by amenity** [comment] 2018-09-17 19:31
Might be addressed by @sergiogcx changes in #471 .

**Comment by amenity** [comment] 2018-10-02 17:56
Duplicate of #598

**Closed** 2018-10-02 17:56 UTC
Labels: Author Interface, Bug Reported, Duplicate, Team: Dev
