### ISSUE TITLE
Coordinate with Dev team to put translated content in alpha by March 9

### ISSUE THREAD

**Issue by courtneyjacinic** [cityofaustin/techstack#133] opened 2018-02-27 20:51 UTC
Monday, 3/5, 1 hour

**Comment by cthibaultatx** [comment] 2018-03-01 16:30
@ashleecoa @LauraTrujillo @courtneyjacinic what are the tasks associated with this task? we got to chatting about it during planning and weren't quite sure :)

**Comment by ashleecoa** [comment] 2018-03-01 16:35
@cthibaultatx @benweatherman stated that the devs will have to input the translated content into the site using JSON. It is not something we can yet input. 

The content exists here: https://drive.google.com/open?id=1rgRRytxDq6KD14kce8I6BdXGJkN87TJA
It is 5 services and 1 department page for Austin Resource Recovery for the three languages. 

- [ ] Add Spanish translation content to alpha
- [ ] Add Vietnamese translation content to alpha
- [ ] Add Arabic translation content to alpha

Does that make sense? Happy to chat more in person.

**Comment by benweatherman** [comment] 2018-03-01 17:01
This seems like a possible duplicate of cityofaustin/techstack#111, or at least related

**Comment by ashleecoa** [comment] 2018-03-01 17:04
@benweatherman I think this one was just for Content to be sure to let Devs know that translations are needed by 3/9. So I can close this one. Yes #111 is for devs to actually input the content.

**Closed** 2018-03-01 17:06 UTC
Labels: Feature: Translation, Short Term, Size: S, Team: Content
