### ISSUE TITLE
Confusion in creating and uploading the official documents in official documents page type

### ISSUE THREAD

**Issue by anukandimalla** [cityofaustin/techstack#3665] opened 2020-01-02 22:15 UTC
## Describe the bug
Multiple documents names can be entered for one single document while uploading the official document.
While uploading the document author can input different “Name of the documents”  
1. While entering the description of the document in "Edit official document page"
2.   While uploading the document from local system "Choose Document >Upload"
This is causing which confusion in creating the official document page and while searching for the official documents  with "Document Title"
In the live page the document named entered in 1 is shown,refer to Screenshot 8 in the google document

## To Reproduce
Please refer to the google document to reproduce and for better understanding
https://docs.google.com/document/d/16E_zJUUC8BAC4wWwlwx0sVGENWjcUd2K74YxZgB2eAI/edit?usp=sharing

## Device and browser

Chrome and Mac

**Comment by desigonz** [comment] 2020-02-14 22:37
Duplicate of #3946

**Closed by desigonz** 2020-02-14 22:37 UTC
Labels: Feature: Document management, Joplin Alpha
